import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import NavbarSearch from './(navbar)/_search';
import { searchForMovies } from './actions';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <NavbarSearch search={searchForMovies} />
        </nav>
        {children}
      </body>
    </html>
  );
}
